// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadTasks() {
  return window['go']['main']['App']['LoadTasks']();
}

export function SaveTasks(arg1) {
  return window['go']['main']['App']['SaveTasks'](arg1);
}
