// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadTasks():Promise<Array<main.Task>>;

export function SaveTasks(arg1:Array<main.Task>):Promise<void>;
